version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: theatre
      POSTGRES_USER: theatreuser
      POSTGRES_PASSWORD: theatrepass
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=theatre
      - DB_USER=theatreuser
      - DB_PASSWORD=theatrepass
      - DB_HOST=db

volumes:
  postgres_data:
